# Generated by Django 5.1.1 on 2024-09-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_emprunter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprunter',
            new_name='Emprunt',
        ),
    ]
